import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import { getSupabaseAdmin } from "@/shared/supabase/admin";

export interface GeneratedDocumentResult {
    url: string;
    filename: string;
    size: number;
    mimeType: string;
}

/**
 * Pre-compiled High Performance PDF Generator for Corvus AI.
 * Runs instantly in memory with zero external wait time.
 */
export async function generateAIICDocumentPDF(options: {
    title: string;
    subtitle?: string;
    authorName?: string;
    sections: Array<{ heading: string; content: string; bulletPoints?: string[] }>;
    tables?: Array<{ headers: string[]; rows: string[][] }>;
    filename?: string;
}): Promise<GeneratedDocumentResult | null> {
    try {
        const { title, subtitle, authorName, sections, tables, filename = `document_${Date.now()}.pdf` } = options;

        const pdfDoc = await PDFDocument.create();
        let page = pdfDoc.addPage([595.28, 841.89]); // A4 dimensions
        const { width, height } = page.getSize();

        const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
        const fontRegular = await pdfDoc.embedFont(StandardFonts.Helvetica);
        const fontOblique = await pdfDoc.embedFont(StandardFonts.HelveticaOblique);

        let y = height - 50;
        const margin = 50;
        const contentWidth = width - margin * 2;

        // Header Banner
        page.drawRectangle({
            x: margin,
            y: y - 10,
            width: contentWidth,
            height: 4,
            color: rgb(0.55, 0.35, 0.95), // Accent Violet
        });
        y -= 25;

        // Title
        page.drawText(title, {
            x: margin,
            y,
            size: 20,
            font: fontBold,
            color: rgb(0.1, 0.1, 0.15),
        });
        y -= 20;

        // Subtitle
        if (subtitle) {
            page.drawText(subtitle, {
                x: margin,
                y,
                size: 11,
                font: fontOblique,
                color: rgb(0.4, 0.4, 0.45),
            });
            y -= 16;
        }

        // Author / Generation metadata
        const dateStr = new Date().toLocaleDateString("en-US", {
            year: "numeric",
            month: "short",
            day: "numeric",
        });
        page.drawText(`Generated by Corvus AI Sentinel for @${authorName || "Member"} · ${dateStr}`, {
            x: margin,
            y,
            size: 9,
            font: fontRegular,
            color: rgb(0.5, 0.5, 0.55),
        });
        y -= 25;

        // Sections
        for (const sec of sections) {
            if (y < 100) {
                page = pdfDoc.addPage([595.28, 841.89]);
                y = height - 50;
            }

            // Section Heading
            page.drawText(sec.heading, {
                x: margin,
                y,
                size: 13,
                font: fontBold,
                color: rgb(0.2, 0.2, 0.3),
            });
            y -= 16;

            // Section Body Text
            const words = sec.content.split(" ");
            let currentLine = "";
            for (const w of words) {
                const testLine = currentLine ? `${currentLine} ${w}` : w;
                const textWidth = fontRegular.widthOfTextAtSize(testLine, 10);
                if (textWidth > contentWidth) {
                    if (y < 80) {
                        page = pdfDoc.addPage([595.28, 841.89]);
                        y = height - 50;
                    }
                    page.drawText(currentLine, {
                        x: margin,
                        y,
                        size: 10,
                        font: fontRegular,
                        color: rgb(0.2, 0.2, 0.25),
                    });
                    y -= 14;
                    currentLine = w;
                } else {
                    currentLine = testLine;
                }
            }
            if (currentLine) {
                if (y < 80) {
                    page = pdfDoc.addPage([595.28, 841.89]);
                    y = height - 50;
                }
                page.drawText(currentLine, {
                    x: margin,
                    y,
                    size: 10,
                    font: fontRegular,
                    color: rgb(0.2, 0.2, 0.25),
                });
                y -= 18;
            }

            // Bullet points
            if (sec.bulletPoints && sec.bulletPoints.length > 0) {
                for (const bp of sec.bulletPoints) {
                    if (y < 80) {
                        page = pdfDoc.addPage([595.28, 841.89]);
                        y = height - 50;
                    }
                    page.drawText(`•  ${bp}`, {
                        x: margin + 10,
                        y,
                        size: 9.5,
                        font: fontRegular,
                        color: rgb(0.25, 0.25, 0.3),
                    });
                    y -= 14;
                }
                y -= 8;
            }
        }

        // Tables
        if (tables && tables.length > 0) {
            for (const table of tables) {
                if (y < 120) {
                    page = pdfDoc.addPage([595.28, 841.89]);
                    y = height - 50;
                }

                const colCount = table.headers.length || 1;
                const colWidth = contentWidth / colCount;

                // Table Header Row
                page.drawRectangle({
                    x: margin,
                    y: y - 4,
                    width: contentWidth,
                    height: 18,
                    color: rgb(0.92, 0.9, 0.98),
                });

                table.headers.forEach((h, idx) => {
                    page.drawText(h, {
                        x: margin + idx * colWidth + 6,
                        y: y,
                        size: 9,
                        font: fontBold,
                        color: rgb(0.2, 0.15, 0.35),
                    });
                });
                y -= 20;

                // Table Data Rows
                for (const row of table.rows) {
                    if (y < 80) {
                        page = pdfDoc.addPage([595.28, 841.89]);
                        y = height - 50;
                    }
                    row.forEach((cell, idx) => {
                        page.drawText(cell || "-", {
                            x: margin + idx * colWidth + 6,
                            y,
                            size: 8.5,
                            font: fontRegular,
                            color: rgb(0.25, 0.25, 0.3),
                        });
                    });
                    y -= 14;
                }
                y -= 15;
            }
        }

        // Serialize PDF to bytes
        const pdfBytes = await pdfDoc.save();
        const buffer = Buffer.from(pdfBytes);

        // Upload to Supabase Storage bucket 'attachments'
        const supabase = getSupabaseAdmin();
        const storagePath = `generated-docs/${Date.now()}_${filename}`;

        const { error: uploadError } = await supabase.storage
            .from("attachments")
            .upload(storagePath, buffer, {
                contentType: "application/pdf",
                upsert: true,
            });

        if (uploadError) {
            console.warn("[PDF_UPLOAD_WARN]", uploadError.message);
            const base64Uri = `data:application/pdf;base64,${buffer.toString("base64")}`;
            return {
                url: base64Uri,
                filename,
                size: buffer.length,
                mimeType: "application/pdf",
            };
        }

        const { data: publicUrlData } = supabase.storage
            .from("attachments")
            .getPublicUrl(storagePath);

        return {
            url: publicUrlData.publicUrl,
            filename,
            size: buffer.length,
            mimeType: "application/pdf",
        };
    } catch (err) {
        console.error("[GENERATE_PDF_ERROR]", err);
        return null;
    }
}
